app:
  name: test

server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8


logging:
  level:
    root: INFO

spring:
  redis:
    host: localhost
    port: 6379
    database: 12
    password: redis
    timeout: 3000
    lettuce:
      pool:
        # Lettuce
        # 连接池最大连接数（使用负值表示没有限制） (CPU cores + 1)
        max-active: 5
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
      # 关闭超时时间
      shutdown-timeout: 100

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:21080/xxl-job-admin
    executor:
      # 注意：这个执行器名称要和 xxl-job 中配置的执行器名称对应上，没有去 xxl-job 新建一个执行器
      appname: xxlTaskExecutor
      ip: ''
      logpath:
      logretentiondays: -1
      # 服务启动会开启一个端口监听
      port: 9997